echo .\pro\demoApp\build\bin\demoApp.exe --c5ll "Flood" --c5fn "fiveCat.txt"
.\pro\demoApp\build\bin\demoApp.exe --c5ll "Flood" --c5fn "fiveCat.txt"
echo " "
echo "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"
echo " "
echo .\pro\demoApp\build\bin\demoApp.exe --line "Hi everybody" --c5ll "Critical"
.\pro\demoApp\build\bin\demoApp.exe --line "Hi everybody" --c5ll "Critical"
echo " "
echo "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"
echo " "
echo .\pro\demoApp\build\bin\demoApp.exe --line "Hi everybody" --c5ll "Warning"
.\pro\demoApp\build\bin\demoApp.exe --line "Hi everybody" --c5ll "Warning"
echo " "
echo "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"
echo " "
echo .\pro\demoApp\build\bin\demoApp.exe --line "Hi everybody" --c5ll "Info"
.\pro\demoApp\build\bin\demoApp.exe --line "Hi everybody" --c5ll "Info"
echo " "
echo "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"
echo
echo .\pro\demoApp\build\bin\demoApp.exe --line "Hi everybody" --c5ll "Debug"
.\pro\demoApp\build\bin\demoApp.exe --line "Hi everybody" --c5ll "Debug"
echo " "
echo "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"
echo
echo .\pro\demoApp\build\bin\demoApp.exe --line "Hi everybody" --c5ll "Trace"
.\pro\demoApp\build\bin\demoApp.exe --line "Hi everybody" --c5ll "Trace"
echo " "
echo "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"
echo " "
echo .\pro\demoApp\build\bin\demoApp.exe --line "Hi everybody" --c5ll "Flood"
.\pro\demoApp\build\bin\demoApp.exe --line "Hi everybody" --c5ll "Flood"
